Update restore.yml

diff --git a/.github/workflows/restore.yml b/.github/workflows/restore.yml
--- a/.github/workflows/restore.yml
+++ b/.github/workflows/restore.yml
@@ -7,17 +7,51 @@ env:
   DOTNET_VERSION: '3.1.404'
   OPERATOR_NAME: "hazelcast-platform-operator"
   BUNDLE_RELEASE_VERSION: 5.13.0
+  RELEASE_VERSION: 5.13.0
 
 jobs:
-  build-and-publish:
+  helm_chart_release:
     runs-on: ubuntu-latest
+    outputs:
+      HELM_CHART_PR_NUMBER: ${{ steps.helm_chart_pr.outputs.HELM_CHART_PR_NUMBER }}
     steps:
-      - name: Checkout 'Hazelcast Operator' Repository
+      - name: Checkout 'main' Branch
         uses: actions/checkout@v4
+        with:
+          repository: cheels/hazelcast-platform-operator
+          token: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
 
-  deploy-dev:
+      - name: Update Chart Version in Main Branch
+        working-directory: helm-charts/hazelcast-platform-operator
+        run: |
+          REPLACED_VERSION=$(echo "$RELEASE_VERSION" | awk -F'.' '{print $1"."$2+1".0"}')
+          echo "REPLACED_VERSION=${REPLACED_VERSION}" >> $GITHUB_ENV
+          sed -i -E -e 's/(version: ).*/\1"'$REPLACED_VERSION-snapshot'"/' -e 's/(appVersion: ).*/\1"'$REPLACED_VERSION-snapshot'"/' charts/hazelcast-platform-operator-crds/Chart.yaml Chart.yaml
+
+      - name: Commit and Push Changes
+        working-directory: helm-charts/hazelcast-platform-operator
+        run: |
+          git config user.email "alexander.borschuk@hazelcast.com"
+          git config user.name "cheels"
+          BRANCH_NAME=update-helm-chart-to-${REPLACED_VERSION}
+          git checkout -b $BRANCH_NAME
+          git add .
+          git commit --signoff -m "$(echo -e "Update helm chart to ${REPLACED_VERSION} version")"
+          git push -u origin $BRANCH_NAME
+
+      - name: Create PR to Main Branch
+        id: helm_chart_pr
+        run: |
+          echo ${{ env.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
+          gh pr create --title "Update Helm Chart Version to ${REPLACED_VERSION}-snapshot" \
+          --label "non-release" \
+          --milestone "${RELEASE_VERSION}" \
+          --body ""
+          echo "HELM_CHART_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
+
+  deploy_bundle:
     runs-on: 'ubuntu-latest'
-    needs: build-and-publish
+    needs: helm_chart_release
     strategy:
       fail-fast: false
       matrix:
@@ -70,10 +104,24 @@ jobs:
           git commit --signoff -m "Update ${OPERATOR_NAME} to ${BUNDLE_RELEASE_VERSION}"
           git push -u origin $BRANCH_NAME
 
-  validate-release:
+      - name: Create PR
+        working-directory: ${{ env.REPO_NAME }}
+        run: |
+          echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
+          gh pr create --title \
+          "operator ${OPERATOR_NAME} (${BUNDLE_RELEASE_VERSION})" --body "" --repo ${REPO_OWNER}/${REPO_NAME}
+          if ! gh pr view ${{ github.event.pull_request.number }} &> /dev/null; then
+              echo "Pull request ${{ github.event.pull_request.number }} not found, retrying in 10 seconds..."
+              sleep 10
+          fi
+          if [ "${{ env.REPO_NAME }}" != "certified-operators" ]; then
+            gh pr comment ${{ github.event.pull_request.number }} --body "/hold"
+          fi
+
+  validate_release:
     if: always()
     name: Approve/Reject release?
-    needs: ['build-and-publish', 'deploy-dev']
+    needs: ['helm_chart_release', 'deploy_bundle']
     runs-on: ubuntu-latest
     environment: 'prod'
     steps:
@@ -81,24 +129,24 @@ jobs:
 
   enable-merge:
     name: Merge PR's
-    needs: validate-release 
-    if: always() && needs.validate-release.result == 'success'
+    needs: validate_release 
+    if: always() && needs.validate_release.result == 'success'
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         include:
           - repo-name: community-operators
-            repo-owner: k8s-operatorhub
+            repo-owner: cheels
 
           - repo-name: certified-operators
-            repo-owner: redhat-openshift-ecosystem
+            repo-owner: cheels
 
           - repo-name: community-operators-prod
-            repo-owner: redhat-openshift-ecosystem
+            repo-owner: cheels
             
           - repo-name: hazelcast-platform-operator
-            repo-owner: hazelcast
+            repo-owner: cheels
     env:
       REPO_NAME: ${{ matrix.repo-name }}
       REPO_OWNER: ${{ matrix.repo-owner }}
@@ -134,10 +182,8 @@ jobs:
               git commit --signoff -m "Update ${OPERATOR_NAME} to ${BUNDLE_RELEASE_VERSION}"
               git push -u origin $BRANCH_NAME
             elif [ "${{ env.REPO_NAME }}" != "certified-operators" ]; then
-              #gh pr comment $PR_NUMBER --body "/hold cancel"
-              echo "PR comment"
+              gh pr comment $PR_NUMBER --body "/hold cancel"
             fi
-          done
 
       - name: Checkout to cheels/hazelcast-platform-operator
         if: ${{ matrix.repo-name }} == 'hazelcast-platform-operator'
@@ -150,20 +196,26 @@ jobs:
         working-directory: ${{ env.REPO_NAME }}
         if: ${{ matrix.repo-name }} == 'hazelcast-platform-operator'
         run: |
-          #echo ${{ env.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
-          #gh pr merge $HELM_CHART_PR_NUMBER --admin
-          echo "PR merge"
+          echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
+          gh pr merge $HELM_CHART_PR_NUMBER --admin
           
   restore-publish:
     name: Revert Release Changes
-    needs: validate-release 
-    if: always() && needs.validate-release.result == 'failure'
+    needs: validate_release
+    if: always() && needs.validate_release.result == 'failure'
+    env:
+      HELM_CHART_PR_NUMBER: ${{ needs.helm_chart_release.outputs.HELM_CHART_PR_NUMBER }}
     runs-on: 'ubuntu-latest'
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Restore the Helm Chart Index
+      - name: Remove ALL
         run: |
-           echo "Restore the Helm Chart Index"
+          echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
+          BRANCH_NAME=${OPERATOR_NAME}-${BUNDLE_RELEASE_VERSION}-${{ github.run_id }}
+          for REPO in "cheels/certified-operators" "cheels/community-operators" "cheels/community-operators-prod"; do   
+             git push origin --delete $BRANCH_NAME
+          done
+            gh pr close $HELM_CHART_PR_NUMBER--repo cheels/hazelcast-platform-operator --delete-branch 2>/dev/null
 
